### ISSUE TITLE
To-do-list for June 30 Milestone and Beyond

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#164]
### Extragalactic Catalog 
Lead group: CS
- [x]  Deliver final version of protoDC2 - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [ ]  Write DESC Note on final validation tests and protoDC2 acceptance -  ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+)
- [x]  Deliver cosmoDC2 catalog including validation test results - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
      
### Instance Catalog
Lead group: SSim
- [x] Finalize DC2 design - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [ ] Validation tests on sprinkler implementation - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [x] Readiness tests in DESCQA and cross-checks with extragalactic catalog readiness tests -  ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) 
- [x] Deliver instance catalog using cosmoDC2 - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 

### Image Catalogs
Lead groups: SSim/CI
- [x] Establish validation protocol for image catalogs - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [x] Deliver Run 1.2p - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [x] Deliver at least partial results for Run 1.2i - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) 
- [x] Start to carry out comprehensive validation tests on Run 1.2x - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [ ] Generating focal planes including the sprinkler code for the RandomWalk galaxies - ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [ ] Prepare DESC Note on outcome

### DM Catalogs
Lead groups: DM-DC2 Task Force/CI/SSim
- [x] Process Run 1.2p with the DM stack - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) 
- [x] Start processing Run 1.2i with DM stack  - ![#ffde00](https://placehold.it/15/ffde00/000000?text=+) ![#6EFF00](https://placehold.it/15/6EFF00/000000?text=+) 
- [x] Establish validation protocol for DM catalogs

### Data serving
Lead groups: CS/SSim/CI, Data Access Task Force
- [x] Finalize match-up strategy for different catalogs
- [x] Implement match-up strategy for different catalogs
- [x] Explore database approach for data serving

**Comment by danielsf** [comment]
Katrin asked me to assemble a checklist of things that need to be done before we are ready to generate InstanceCatalogs (and thus, images) from CosmoDC2.  This is what I have come up with.  Feel free to edit this, especially if I @-ed you.

## InstanceCatalog infrastructure
- [ ] Update `sims_GCRCatSimInterface` to reflect the ways that CosmoDC2 is not protoDC2 (e.g. we no longer have to rotate the field of view; this could be as simple as setting the rotation parameters to 0, but we should check that there aren't any more protoDC2 peculiarities) (@danielsf @jchiang87 )

## Adding models to CosmoDC2
- [ ] Generate AGN variability parameters from the CosmoDC2 extragalactic catalog (@danielsf)
- [ ] Run the scripts which will associate CosmoDC2 with sprinkled lensing systems (@jbkalmbach)
- [ ] Run the scripts which will derive the distribution of supernova/supernova-host parameters from the CosmoDC2 extragalactic catalog (@rbiswas4)
- [ ] Run the scripts that will associate galaxy knot parameters with the galaxies in the CosmoDC2 extragalactic catlaog (@EiffL )

## Validating inputs to InstanceCatalogs
- [ ] Validate that the distribution of AGN variability parameters looks sane (in consultation with concerned working groups) (@danielsf)
- [ ] Write and execute a DESCQA test to convince ourselves that the distribution of dust parameters in the CosmoDC2 extragalactic catalog is reasonable (@abensonca @egawiser )
- [ ] Generate the truth catalog from the CosmoDC2 extragalactic catalog, including transients (@danielsf @rbiswas4 @jbkalmbach @yymao)
- [ ] Write the DESCQA scripts that will verify InstanceCatalogs against the truth catalog, so that we can be confident that we are correctly generating the InstanceCatalogs (@jbkalmbach @yymao )

**Comment by katrinheitmann** [comment]
@jbkalmbach @danielsf @yymao This is an old issue, but I am wondering if all of the sprinkler tests have been done and test results have been documented? Thanks!

**Comment by danielsf** [comment]
In the past I have generated sprinkled InstanceCatalogs and run Bryce's validation scripts on them to make sure that the resulting light curves are sane.

I intend to do that again once we enter the production phase for uDDF InstanceCatalogs.

Closing this issue seems reasonable (I do not need it left open to remind me to validate the sprinkled InstanceCatalogs).
