### ISSUE TITLE
Validation checklist of 1.2p and 1.2i as preparation for Run 2.0

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-production#254]
Given that we want to run 2.0i during the first weeks of September, we have to have check 1.2p and 1.2i results (especially the latter) to make sure that we don't waste CPU hours. Here I am putting a checklist of pieces of code that we want to be ready by then. Feel free to add items to the list if something is missing.

- [ ] Visual inspection of 1.2i images: Right now some images have been ingested using `makeFpSummary`. Once we have a larger dataset we should try to distribute it and check that there are no outstanding issues. @kadrlica and @SimonKrughoff have been working on this.

- [ ] GCR ingestion of 1.2i object catalog. This would be nice to have in order to use the current infrastructure, if not, we would have to create a butler-based reader (which will be necessary for the `src` catalogs anyway). @yymao and @wmwv. What are your thoughts on this?

- [x]  Astrometry and photometry tests at coadd level: These are implemented in [this PR](https://github.com/LSSTDESC/descqa/pull/124). @fjaviersanchez is working on this. 

- [x] Astrometry and photometry tests on single visits: Standalone code working (results [here](https://github.com/LSSTDESC/DC2-production/issues/168#issuecomment-410325141)

- [x] Image background checks [here](https://github.com/LSSTDESC/descqa/pull/104). @fjaviersanchez is working on this.

- [ ] Image level tests: image has sources. @rmjarvis is working on this.

- [ ] Shape tests at coadd level: @rmjarvis is working on this.

- [ ] Sensor and atmospheric effects validation at coadd and single visit catalog level. Some tests have been suggested [here](https://github.com/LSSTDESC/descqa/issues/127). @andrewkbradshaw, @rmjarvis, @ricardogando, and @fjaviersanchez will work on these.

- [ ] Quick end-to-end analyses. @EiffL and @fjaviersanchez have scripts to check some features of the data (3x2-pt related: e.g., depth+power-spectra, rho statistics, etc). @ricardogando and @andrewkbradshaw, do you have any ideas for quick end-to-end analyses?
  
- [ ] Other?

**Comment by wmwv** [comment]
@fjaviersanchez I'm happy to prepare GCR-readable DPDD Object Table outputs as soon as the 1.2[p,i] coadds + forced photometry are ready.

When they become available, please ping me as to where on NERSC they are available and I will be happy to generate files.

If they are already ready at NERSC, my apologies for not tracking that.

**Comment by jmeyers314** [comment]
We need to look at the PSF ellipticities and sizes (to sanity check the code [here](https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/atmPSF.py#L97)).  I semi-arbitrarily moved the ground layer there from 0 m to 200 m in order to weaken the correlations, which visually looked too large on some earlier test runs (outside of imSim).  We need to confirm this is a reasonable adjustment.  PSF whisker plots, histograms, and correlation functions would be very helpful in assessing this.

**Comment by katrinheitmann** [comment]
@fjaviersanchez I think this issue should be closed, right? If there is something left over that we should still do, probably it should go into one of the other validation issues about 2.1i? Thanks!
