### ISSUE TITLE
Sprinkler Checklist for Run 2.0

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#257]
These are the items that need to be completed to get the sprinkler ready for Run 2.0. If I forgot anything please add it.

- [x] Add Host Galaxy functionality into `sims_GCRCatSimInterface` (Issues #61 and #62)
  - [x] Merge LSSTDESC/sims_GCRCatSimInterface#56

- [x] Sprinkler Instance Catalog Tests (LSSTDESC/Twinkles#467, #139)
  - [x] Merge LSSTDESC/Twinkles#473

- [ ] Update notebooks that rely upon extragalactic catalog (LSSTDESC/Twinkles#477, #255)
  - [x] Get approval and merge LSSTDESC/Twinkles/pull/478
  - [ ] Validate that OM10 systems matched in notebook are a useful distribution of systems (@jiwoncpark will run SLRealizer to generate light curves and check)

- [x] Create caches of `galaxy ids` for Run 2.0 (Will follow from notebooks above)
  - [x] Verify that sprinkler modified `galaxy ids` will not clash with `galaxy ids` from extragalactic catalog (Issue: LSSTDESC/Twinkles#474)
  - [x] Make sure that sprinkler galaxies will not appear in knots catalog. (Issue #128)

- [x] Create necessary input for host galaxy lensing (Issue #256)
  - [x] @jbkalmbach needs to create host galaxy catalog for @linan7788626 
  - [x] @linan7788626 will create inputs for the code in LSSTDESC/sims_GCRCatSimInterface#56

**Comment by katrinheitmann** [comment]
Since the sprinkler is now integrated and tested in Run 2.1i, I believe we can close this issue. @jbkalmbach feel free to reopen or add new issues to DC3. Thanks!
