### ISSUE TITLE
workflow Run 2.0 WFD checklist 

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#262]
- [x] Final workflow tests
- [x] Set up visit directories
- [x] Make first bundle list
- [x] Transfer instance catalogs from NERSC to ALCF
- [x] Re-generate singularity image with newest imSim version

**Comment by katrinheitmann** [comment]
The workflow set up was finished and worked well so far. We have identified some opportunities for improvement. Those are tracked in a different github repo.
