### ISSUE TITLE
Checklist before resuming 2.1i

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-production#312]
Let's try to capture what are the issues/concerns about the data before resuming 2.1i:

 - [ ] PSF size (issue #313 )

- [x] PSF residual correlation: In a single visit, when compared to the [LSST-SRD](https://docushare.lsst.org/docushare/dsweb/Get/LPM-17) we don't pass the TEx criteria. Caveat: The criteria is for **full survey data**. After discussing with @rmjarvis, he pointed out that the values should decrease as ~N (N number of exposures) in the coadds. If we increase the tolerance by a factor of ~100, the measured residuals pass the criteria.

* Absolute astrometry and photometry are in compliance with the SRD.
* Depth in compliance with the SRD and OpSim expectation. Concern: We'll have to re-check this when the new PSFs are in place since a larger PSF should reduce the depth.
* PSF ellipticity, |e|, in compliance with the maximum values in the SRD. When we change the PSF we will have to re-check this and see if the distribution still looks good.

All, are there other issues/concerns? What other tests can we do with these `calexps`? Are there other checks to be done using the `centroid` files?

To do:

 - [ ] Try to run `validate_drp` to cross-check the results on the TEx criteria.

**Comment by katrinheitmann** [comment]
@fjaviersanchez I think since we restarted now Run 2.1i, we can now close this, right? Thanks!
