### ISSUE TITLE
Run2.2i Production

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#368]
Run2.2i

    300 sq degrees, 5 years, no-AGNs in WFD

**Checklist**
Simulation

- [ ] Cross check Run2.1.1i simulation produced at NERSC and on Grid See: https://github.com/LSSTDESC/DC2-imsim-eu-grid/issues/3
- [ ] Finalize the Run2.2i Processing Plan See: https://github.com/LSSTDESC/DC2-production/issues/369
- [ ] Retrieve (y1-y5 or y6-y10) Run2.1i instance catalogs from HPSS at NERSC
- [ ] Update existing Run2.1i instance catalogs and comment out AGNs
- [ ] Store updated Run2.2i instance catalogs to HPSS at NERSC 
- [x] Create new lsst-sims release with GalSim 2.2.1
- [x] Create new imSim Docker image and verify correct version of `throughputs` is used
- [ ] Test new imSim Docker image
- [ ] Determine whether WFD area covering the DDF field done with or without AGN 
- [ ] Implement sufficient configuration control across sites running sims See: https://github.com/LSSTDESC/ALCF_1.2i/issues/35

DM DRP

- [ ] CC Prep https://github.com/LSSTDESC/ImageProcessingPipelines/issues/126
- [ ] Create new `obs_lsst` branch for `dc2/run2.2`, including all mods from `dc2/run2.1`
- [ ] Tag ImageProcessingPipelines `dc2/run2.1` branch as used for Run2.1.1i
- [ ] Finish full DRP pipeline implementation
- [ ] Create new `ImageProcessingPipelines` branch named `dc2/run2.2`, which includes all `dc2/run2.1` modifications, and the current full DRP pipeline
- [ ] Check DC2-production readiness for object and metacal parquet files creation and merging
- [ ] Validate DMstack v18.1.0 running in SRS Workflow, including use of gcc 7.3.1 binaries

Infrastructure

- [ ] Free up adequate space for simulation and processed data at NERSC in `projecta`
- [ ] Estimate [ simulation output space](https://github.com/LSSTDESC/DC2-production/issues/368#issuecomment-531253044) required on CSCRATCH at NERSC
- [ ] Store simulation output checkpoint files to HPSS at NERSC
       possibly using the sim processing pipeline, see: https://github.com/LSSTDESC/ALCF_1.2i/issues/34

**Comment by villarrealas** [comment]
@cwwalter Apologies - I sometimes think faster than I type apparently. I **don't** think we'll need to write anything new on tape. That seems extraneous.

**Comment by heather999** [comment]
I tend to agree with Katrin, that having one copy of the instance catalogs which is precisely what we used for the final production should be on tape.  We don't need two copies though, so this could be a replacement.  I'm also not looking to create more work :) so alternatively, we can insert a README with the tape copy and indicate what we did, including whatever script is used to comment out those AGNs.
The checkpoint files are large.  We will need to clear those off even CSCRATCH as soon as possible.  In fact we should make an estimate of the output size for the simulation, just to be sure we have enough space on CSCRATCH.  I'd like to migrate things to tape as soon as possible - especially in the case of the checkpoint files.

**Comment by villarrealas** [comment]
My stance would be it is better to maintain the original instance catalogs **and** have a README that notes specifically that the runs labeled `no-agn` have a specific line commented out on each file, but I could see the argument for having a final production version saved to tape. I just worry it seems like an excessive amount of work to pull from tape, edit, repackage, and send back in when the file difference is literally a single # character.

**Comment by cwwalter** [comment]
Yes, but if you replace it then you want have the instance catalog for the first 3 years :)

I think you either want both or just record what you did / or push the script that did it.  Since Antonio is going to handle it int he workflow that is also being recorded.

**Comment by heather999** [comment]
I am a superstitious soul :)  We have to pull from tape anyhow, similarly the edit is going to occur.  The sim workflow will be handling the update to the instance catalogs?  Presumably, a copy will be retained on scratch and then it's just a matter of copying it to tape.  But I am wondering then - will the Grid folks similarly be updating their workflow to update the instance catalogs or is what Antonio doing going to be shared and used by all? 
We've already had a situation where the Grid folks had to recopy instance catalogs from HPSS due to an incomplete transfer.  I'd like to have one canonical copy.  So we'd retain the original Run2.1i instance catalogs and also Run2.2i's.  We have the space on tape - that's not an issue.

**Comment by villarrealas** [comment]
To address the question of space:

While storing AGN checkpoints, a single sensor-visit is roughly ~124 MB in size, with some variance. So we're looking at roughly 23.5 GB per visit of 189 sensors. Assuming we try to keep the outputs down to ~50 TB at a time, we're looking at processing roughly half a year in a single step. I think that if we attempted to complete an entire year (ranging from ~3000 visits to ~5000 visits), we'd risk blowing out our existing quota.

**Comment by heather999** [comment]
Can we add writing the AGN checkpoints to tape at the end of the processing of a single step?  That might even be "Free" in terms of Cori hours.  We can also ask for a temporary increase in CSCRATCH quota, this would seem to be a good reason.

**Comment by villarrealas** [comment]
With the current production pipeline, it would have to be manually fired after runs; I don't see why I shouldn't be able to put together a script to automate the Globus transfers for just that subsection though. It wouldn't impact the recognition of jobs as complete or not with the pipeline either.

**Comment by cwwalter** [comment]
Antonio, I assume you already know about this... but just in case here are some instructions on command line globus transfers which could be embedded in your code:

https://support.opensciencegrid.org/support/solutions/articles/5000632397-data-transfer-to-osg-connect-with-globus#using-the-globus-online-command-line-interface

**Comment by boutigny** [comment]
@villarrealas 
>  For off-site running, I recommend letting me lock down the run on NERSC, at which point I will update our repository which includes all configuration parameters, which we can then pass forward to other sites and make certain that they are converged. I believe they were also carrying out the Run 2.1.1i no-agn test though, so we should also have some comparison on that front, I believe.

On top of configuration parameters we also need to record the submission scripts themselves (at NERSC, at ANL and on the grid). The fact that there were some misunderstanding on this point led to a waste of grid  resources. 
I understand that from now on there will be some early validation to make sure that the 3 configurations are identical, but keeping track of the submission scripts is essential anyhow.

**Comment by villarrealas** [comment]
@heather999 I see your point about the fact that the edit will happen at some point regardless. The way I see it is there are two options:

1) We pull all instance catalogs off tape, manually edit them, put them back on tape. My script to manually go through and edit each file is admittedly slow currently; but I think that is dominated by the fact that I needed to only unpackage specific instance catalogs more than any in-place file editing. That being said, it is a bit of work+time waiting for transfers and unpacking.

2) We let other people do the editing as they pull them (and possibly reuploading to tape). This is less work up front, but ultimately the same amount of work overall.

In either case, I can point to the modification script, but really it is just a whole bunch of python run `sed` commands.

@boutigny I think you're referring to the difficulty of comparison between NERSC/ANL + Grid, which is driven by the fact that they do not make use of the same Parsl/Singularity driven workflow. So in that case, I think what we do not want is the submission scripts, but the following list:
1. The imsim driver python script.
2. Examples of the final calls on the imsim driver.
3. The imsim configuration files that are being called in the above examples.

1+3 should be intrinsically in the Github repository that I will upload once things are configured for running with updated imSim+GalSim+etc, but I'll make sure to get an inclusion of 2 somewhere in there just for ease of comparison.

**Comment by cwwalter** [comment]
I think there is at least one unified imSim driver script now correct?

**Comment by villarrealas** [comment]
Correct, last I checked the UKGrid group has switched to using the driver we are using in production at NERSC/ALCF.

**Comment by boutigny** [comment]
@villarrealas yes, I meant the imsim driver script, not the submission script.

**Comment by heather999** [comment]
Closing this issue and moving checklist to Confluence: https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Run2.2i
