### ISSUE TITLE
Strongly Lensed Transient and Galaxy Sprinkler

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2-production#56]
In this epic we track the development of the strongly lensed transient and galaxy sprinkler, a software pipeline that will modify instance catalogs produced by CatSim to include strongly lensed supernovae, AGNs, and galaxies. These modified instance catalogs will be passed to the kind folks in the CI working group to generate images of the uDDF for DC2. 

The principals on this project are 

@rbiswas4 - handling time-variable source models
@linan7788626 - handling image generation of lensed host galaxies
@dannygoldstein - handling host, lens, and transient population models
@jbkalmbach - handling instance catalog modification to include images of lensed transients 
@mpwiesner - handling instance catalog modification to include lensed host galaxies

- [x] #58 Transient Catalog Generation
- [x] #59 Time-Evolving SEDs of Strongly Lensed Transients
- [x] #60 Sprinkle images of strongly lensed transients into instance catalogs
- [x] #61 Generate lensed images of strongly lensed transient host galaxies
- [x] #62 Modify instance catalogs to contain lensed host galaxy images
- [x] #64 Fix AGN SED redshift issue in sprinkler
- [x] #68 Small Sprinkler test catalog

**Comment by drphilmarshall** [comment]
Sweet! Paging @jchiang87 from CI so they can follow along.

**Comment by jchiang87** [comment]
In turn, I'm pinging @danielsf since this mostly implicates CatSim.   We'll all need to coordinate everything in the instance catalog generation step of course.

**Comment by dannygoldstein** [comment]
Hi @TomGlanzman, our group should be ready to deliver the sprinkler code (with host galaxy lensing) by Friday March 30. We would like to incorporate it into Run 1.2 and perhaps do a few smaller-scale tests beforehand. Could you please let us know how we should proceed with the handoff?

**Comment by jchiang87** [comment]
Just to set the scene a little for Tom's benefit:  In addition to the new sprinkler code, we'd need modifications to the `sims_GCRCatSimInterface` package so that `generateInstCat.py` can generate the instance catalogs that include these strongly lensed sources, along with the ancillary files that are needed, such as the postage stamp FITS files for the lensed images.  However, since those are static images, I assume they could be generated once and reused for the visits that need them rather than be regenerated for each visit.   In any case, we should coordinate with Tom as to where those FITS files will be located for the phosim pipeline to find them.

**Comment by TomGlanzman** [comment]
A question about the FITS files for lensed images: is there a way to prepare *all* of those files in advance?  Or must they be produced during catalog generation?

Are there yet other new ancillary files needed and, if so, could their characteristics and use be summarized?

**Comment by jbkalmbach** [comment]
Yes, we can produce all of those files in advance and @linan7788626 is actually preparing them right now for the run 1.2p dataset.

**Comment by mpwiesner** [comment]
We have not yet adopted a naming convention for these instance files.  Is there a preferred method?

**Comment by jchiang87** [comment]
The instance catalogs for each visit need to be generated using the `generateInstCat.py` script in https://github.com/LSSTDESC/sims_GCRCatSimInterface.   Note that phosim seems to need coordinates in "geocentric" coordinates which means each visit will have slightly different ra, dec numbers.  @jbkalmbach knows how to update that code to have it generate new instance catalogs.

**Comment by TomGlanzman** [comment]
I am guessing that since generateInstCat.py is creating the catalog files, the naming convention will not change...?

**Comment by jchiang87** [comment]
As far as the phosim pipeline is concerned, that is correct.  The `phosim_cat_*.txt` files will have `includeobj` lines that will point to file names corresponding to the needed files for that visit.   Those file names need not be the same as Run1.1p.

**Comment by danielsf** [comment]
I am going to close this issue.  We are able to generate InstanceCatalogs with the strongly lensed transients in it.
